# Generated by Django 3.1.6 on 2021-02-08 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finatic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lust',
            options={'ordering': ['-date']},
        ),
    ]
