# Generated by Django 3.1.6 on 2021-02-12 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finatic', '0002_auto_20210208_0424'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lust',
            options={'ordering': ['date']},
        ),
    ]
