# Generated by Django 3.2.9 on 2021-11-24 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finatic', '0003_auto_20210212_0155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lust',
            options={'ordering': ['-time']},
        ),
        migrations.AlterField(
            model_name='lust',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
