# Generated by Django 3.2.9 on 2021-11-25 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finatic', '0004_auto_20211124_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReachMe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'ReachMe',
            },
        ),
        migrations.AlterModelOptions(
            name='lust',
            options={'ordering': ['-time'], 'verbose_name_plural': 'Lust'},
        ),
    ]
